import { Box, Container } from '@chakra-ui/react'
import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Section from '../components/section'
import Paragraph from '../components/paragraph'
// import Main from '../components/Layout/main'
const Home :NextPage = () => {
  const MyImage = styled.span`
  display:inline-block;
  width:60%;
  img {
    transition: 200ms ease;
    border-radius:8em;
  }
  `
  return (
    <>
      <Head>
        <title>Future Itsuki-homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

      <Box 
      textAlign="center">
      <Box
      borderRadius="lg"
      mb={6}
      p={3}
      textAlign="center"
      bg="blackAlpha.300"
      css={{backdropFilter:'blur(10px)'}}
      >
        Welcome, My Portfolio, come Japan
      </Box>
      <MyImage>
        <Image 
        src="/images/me.jpg"
        width={150}
        height={150}
        />
      </MyImage>
    </Box>
    <Section>
      <Paragraph>
        Hello World
      </Paragraph>
    </Section>
  </Container>
    </>
  )
}

export default Home
