import {
  Button,
  Container,
  Flex,
  Heading,
  HStack,
  Link,
  Image,
  Box,
  Center,
  Text,
  Stack,
  List,
  ListItem,
  ListIcon,
  useColorModeValue,
} from "@chakra-ui/react";
import { CheckIcon } from "@chakra-ui/icons";

import { GiFruitTree } from "react-icons/gi";
import {
  SiJavascript,
  SiPhp,
  SiReact,
  SiLaravel,
  SiNextdotjs,
  SiTailwindcss,
  SiWordpress,
  SiThreedotjs,
  SiBootstrap,
  SiOpengl,
  SiNodedotjs,
  SiJquery,
  SiTwitter,
} from "react-icons/si";

import Head from "next/head";

import Section from "../components/section";
import Paragraph from "../components/paragraph";
import Card from "../components/card";
import { ListContent, ListHeading } from "../components/list";
import { IoLogoGithub, IoLogoInstagram } from "react-icons/io5";
const Home = () => {
  return (
    <>
      <Head>
        <title>Future Itsuki-homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Section>
          <Box
            borderRadius="lg"
            mb={6}
            p={3}
            textAlign="center"
            bg="blackAlpha.100"
            css={{ backdropFilter: "blur(10px)" }}
          >
            Welcome, My Portfolio, come Japan
          </Box>
          <Box position="relative">
            <Flex display="flex">
              <Heading as="h2" fontWeight="bold" letterSpacing={2}>
                Sato Itsuki
              </Heading>
              <Box>
                <GiFruitTree fontSize={36} />
              </Box>
            </Flex>
            <HStack display={{ base: "block", md: "flex" }}>
              <Paragraph>Digital Craftsman ( FrontDeveloper )</Paragraph>
              <Box align="center">
                <Image
                  src="/images/me.jpg"
                  maxWidth="200px"
                  maxHeight="200px"
                  marginTop={8}
                  borderWidth={3}
                  borderRadius="full"
                  borderStyle="solid"
                  borderColor="green.200"
                />
              </Box>
            </HStack>
          </Box>
        </Section>
        <Section delay={0.1}>
          <Heading as="h3" mb={8} fontSize={24}>
            Work
          </Heading>
          <Paragraph>
            Takuya is a freelance and a full-stack developer based in Osaka with
            a passion for building digital services/stuff he wants. He has a
            knack for all things launching products, from planning and designing
            all the way to solving real-life problems with code. When not
            online, he loves hanging out with his camera. Currently, he is
            living off of his own product called Inkdrop. He publishes content
            for marketing his products and his YouTube channel called "Dev as
            Life" has more than 100k subscribers.
          </Paragraph>
          <Box textAlign="center" mt={8} mb={8} p={6}>
            <Button bg="green.200">
              <Link href="/work">My-Portfolio</Link>
            </Button>
          </Box>
        </Section>
        <Section delay={0.2}>
          <Box>
            <Heading as="h3" mb={8} fontSize={32}>
              Skill
            </Heading>
            <ListHeading>Language</ListHeading>
            <ListContent>
              <SiPhp fontSize={32} />
              <SiJavascript fontSize={24} />
            </ListContent>
            <ListHeading>Framework</ListHeading>
            <ListContent>
              <SiLaravel fontSize={24} />
              <SiWordpress fontSize={24} />
              <SiNextdotjs fontSize={24} />
            </ListContent>
            <ListHeading>Library</ListHeading>
            <ListContent>
              <SiJquery fontSize={24} />
              <SiReact fontSize={32} />
              <SiNodedotjs fontSize={24} />
              <SiTailwindcss fontSize={24} />
              <SiBootstrap fontSize={24} />
              <SiThreedotjs fontSize={24} />
              <SiOpengl fontSize={32} />
            </ListContent>
          </Box>
        </Section>
        <Section delay={0.4}>
          <Box textAlign="center">
            <Heading as="h3" mb={8} fontSize={32}>
              Price
            </Heading>
            <Card>
              <Center py={6}>
                <Box
                  maxW={"250px"}
                  maxH={"500px"}
                  bg={useColorModeValue("white", "gray.800")}
                  boxShadow={"2xl"}
                  rounded={"md"}
                  overflow={"hidden"}
                >
                  <Stack
                    textAlign={"center"}
                    p={6}
                    color={useColorModeValue("gray.800", "white")}
                    align={"center"}
                  >
                    <Text
                      fontSize={"sm"}
                      fontWeight={500}
                      bg={useColorModeValue("green.50", "green.900")}
                      p={2}
                      px={3}
                      color={"green.500"}
                      rounded={"full"}
                    >
                      Webサイト制作
                    </Text>
                    <Stack
                      direction={"row"}
                      align={"center"}
                      justify={"center"}
                    >
                      <Text fontSize={"3xl"}>¥</Text>
                      <Text fontSize={"4xl"} fontWeight={800}>
                        5000
                      </Text>
                      <Text color={"gray.500"}>/1ページ</Text>
                    </Stack>
                  </Stack>
                  <Box
                    bg={useColorModeValue("gray.50", "gray.900")}
                    px={6}
                    py={10}
                  >
                    <List spacing={3}>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        1ページ追加+3000円
                      </ListItem>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        JavaScriptも対応しています
                      </ListItem>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        既存ページ一部コーディング修正3000円~
                      </ListItem>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        ページコーディング作成　１ページ（極小規模） ⇒ 4500円～
                      </ListItem>
                    </List>
                  </Box>
                </Box>
              </Center>
              <Center py={6} m={4}>
                <Box
                  maxW={"250px"}
                  maxH={"500px"}
                  bg={useColorModeValue("white", "gray.800")}
                  boxShadow={"2xl"}
                  rounded={"md"}
                  overflow={"hidden"}
                >
                  <Stack
                    textAlign={"center"}
                    p={6}
                    color={useColorModeValue("gray.800", "white")}
                    align={"center"}
                  >
                    <Text
                      fontSize={"sm"}
                      fontWeight={500}
                      bg={useColorModeValue("green.50", "green.900")}
                      p={2}
                      px={3}
                      color={"green.500"}
                      rounded={"full"}
                    >
                      ECサイト
                    </Text>
                    <Stack
                      direction={"row"}
                      align={"center"}
                      justify={"center"}
                    >
                      <Text fontSize={"3xl"}>¥</Text>
                      <Text fontSize={"4xl"} fontWeight={800}>
                        70000
                      </Text>
                      <Text color={"gray.500"}>/1ページ</Text>
                    </Stack>
                  </Stack>
                  <Box
                    bg={useColorModeValue("gray.50", "gray.900")}
                    px={6}
                    py={10}
                  >
                    <List spacing={3}>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        Laravelを使用して構築
                      </ListItem>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        既存ページ一部コーディング修正3000円~
                      </ListItem>
                      <ListItem>
                        <ListIcon as={CheckIcon} color="green.400" />
                        ページコーディング作成　１ページ（極小規模） ⇒ 4500円～
                      </ListItem>
                    </List>
                  </Box>
                </Box>
              </Center>
            </Card>
            <Button bg="green.200" mt={8}>
              <Link href="/contact">Request a job</Link>
            </Button>
          </Box>
        </Section>
        <Section>
          <Heading as="h4">My SNS</Heading>
          <Box mt={6}>
            <Link target="_blank" href="https://twitter.com/8tfGpQ99poWMQFN">
              <HStack>
                <SiTwitter />
                <Text>Twitter</Text>
              </HStack>
            </Link>
          </Box>
          <Box mt={6}>
            <Link target="_blank" href="https://github.com/futureituki">
              <HStack>
                <IoLogoGithub />
                <Text>Github</Text>
              </HStack>
            </Link>
          </Box>
          <Box mt={6}>
            <Link target="_blank" href="https://github.com/futureituki">
              <HStack>
                <IoLogoInstagram />
                <Text>Instagram</Text>
              </HStack>
            </Link>
          </Box>
        </Section>
      </Container>
    </>
  );
};

export default Home;
